### ISSUE TITLE
Fallbeispiel

### ISSUE THREAD

**Issue by juliandierker** [juliandierker/yUOShi#114]
In den MC-Aufgaben zum Fallbeispiel sollen Aussagen auch "neutral" gewertet werden können. Beim Grading sollen diese nicht zu einem Scheitern der Aufgabe führen und in der Lösungsansicht "gelb" markiert werden.

2 weitere SchüerInnen hinzufügen

**Comment by SmokyZone** [comment]
Was genau ist hier mit den "2 weiteren SchülerInnen hinzufügen"  gemeint?
Falls das fertig ist / sich erledigt hat, bitte das Issue schließen. Danke :)
