### ISSUE TITLE
Meinungs-Umfrage

### ISSUE THREAD

**Issue by juliandierker** [juliandierker/yUOShi#119]
- [x]  Hervorheben (sollten sich von den MC unterscheiden)

- [x]  nicht aufgabe lösen, sondern Antwort abschicken

- [x]  Bemerkung unter sonstiges (freitext)

- [x]  Ergebnisse auswerten + anzeigen

**Comment by SmokyZone** [comment]
Soll hier dann ein Survey-Component gemacht werden, welches eine ClozeView und ein Textfeld für Bemerkung hat?
