### ISSUE TITLE
X-Wert-Aufgabe

### ISSUE THREAD

**Issue by juliandierker** [juliandierker/yUOShi#122]
- [x]  Formel anzeigen

- [x]  Auf 4 SuS kürzen

- [x]  Folgeaufgabe immer - dafür aber ohne Zahlen, sodass man im Zweifelsfall zurück muss

**Comment by SmokyZone** [comment]
Ist damit das XWert Multiple Choice gemeint?

**Comment by SmokyZone** [comment]
und wofür steht SuS?

**Comment by SmokyZone** [comment]
Ist Punkt 3 richtig durchdacht?

**Comment by SmokyZone** [comment]
Was soll kritische Formelbetrachtung sein???

**Comment by Miribur** [comment]
> und wofür steht SuS?

Schülerinnen und Schüler
