### ISSUE TITLE
Aufgabe intr/extr fertig stellen

### ISSUE THREAD

**Issue by juliandierker** [juliandierker/yUOShi#13]
- [ ]  Dragelemente vervollstädnigen

- [ ]  Zwischenpunkte ab (x) Elementen?

- [ ]  Fehler möglich aber Elemente verschwinden -> Nutzer bekommt Feedback

**Comment by Miribur** [comment]
in dem Dokument sind noch mehr Sätze... lassen sich die noch dazu nehmen?
mir würde es reichen, wenn 2-3 zugeordnet werden sollen, aber mehr können
