### ISSUE TITLE
scroll Probleme, responsivität

### ISSUE THREAD

**Issue by Miribur** [juliandierker/yUOShi#140]
bei den "größeren" tasks, wie memory, zuordnung intrinsisch / extrinsisch kann ich auf meinem mac nicht bis nach unten schauen, finde weder den button "Aufgabe lösen" noch einige Elemente

- [x] größe anpassen, sodass nichts mehr am ende des Screens abgeschnitten ist und darauf achten, dass die Tasks scrollable sind.

- [x] Tasks etwas weiter nach Oben verschieben und die Buttons "Nächste|Vorherige Aufgabe" so verschieben, dass sie nicht mehr die Tasks verdecken

**Comment by SmokyZone** [comment]
Gibt es dazu evtl. einen Screenshot? 
Was hat dein mac denn ca. für eine Bildschirmhöhe? (Zum reproduzieren)

**Comment by Miribur** [comment]
Hallo Sebastian,
12 inch
