### ISSUE TITLE
Offenes Antwortformate

### ISSUE THREAD

**Issue by Miribur** [juliandierker/yUOShi#143]
- [x] bei der Umfrage als Antwortmöglichkeit (sonstiges ________)

- [x] auf den Lernkarten (Notizen_________)

- [x] am ende des Quests (Reflexion: wie hast du das Level erlebt? (Platzhalter) )

**Comment by SmokyZone** [comment]
Das Sonstiges Feld ist mit dem neuen Survey Component (#144) auch schon mit eingebaut
