### ISSUE TITLE
Lernkarten content einfügen

### ISSUE THREAD

**Issue by juliandierker** [juliandierker/yUOShi#150]
Mysharelink:

**Comment by Miribur** [comment]
es gibt eine Übersicht über Lernkarten und Content --> Motivation --> Lernkarten,
da sind auch potentielle Bilde dabei

**Comment by SmokyZone** [comment]
Wo genau müssen die Lernkarten angelegt werden?

**Comment by Miribur** [comment]
Nach jedem Tag Task!
