### ISSUE TITLE
Eingangsbegrüßung

### ISSUE THREAD

**Issue by Miribur** [juliandierker/yUOShi#167]
<3 Willkommen an der yUOShi Schule! Wir freuen uns, dich als neue Lehrkraft begrüßen zu dürfen. Schaue dich gerne um. Was gibt es neues im Klassenzimmer?

**Comment by SmokyZone** [comment]
Überlegung: Beim Login das Datum Speichern und den Nutzer immer wieder begrüßen, wenn das jetzige Datum nicht das lastLogin Datum ist.
