### ISSUE TITLE
Aufforderung nach Fallpräsentation

### ISSUE THREAD

**Issue by Miribur** [juliandierker/yUOShi#182]
nach dem letzten vorgestellten Fall ein letztes Modal

Bild --> Lehrerin (das gleiche wie am ANfang)

Um den Schüler*innen helfen zu können, solltest du erst einmal verstehen, welche psychischen Dynamiken eine Rolle spielen. Setze du dich im folgenden mit den Grundlagen der Motivation auseinander!

**Comment by juliandierker** [comment]
Sehr gut, nun hast du dich mit dem Thema Motivartion auseinandergesetzt. Du kannst dich jetzt den anfangs vorgestellten Schüler*innen widmen und sie in die Sprechstunde einladen.
