### ISSUE TITLE
Exposée fertigstellen und BA anmelden

### ISSUE THREAD

**Issue by xyng** [juliandierker/yUOShi#201]
Das Exposée muss noch überarbeitet und damit dann die BA angemeldet werden.

**Comment by juliandierker** [comment]
Du pusht nochmal das neue Expose?
https://github.com/xyng/bachelor-thesis

**Comment by xyng** [comment]
Das war da eigentlich schon oben.
BA ist angemeldet, und das Exposé ist definitiv im Git und per Slack hast du ja auch eine PDF bekommen 😊
