### ISSUE TITLE
Fortschritt Button in die Top Menu Bar (Tablet und Mobile)

### ISSUE THREAD

**Issue by SmokyZone** [juliandierker/yUOShi#202]
Der "Fortschritt" Button für das Stepper Modal (Name: StepperModalIcon) nimmt in der Tablet und Mobile View sehr viel platz weg. Um den Platz zu sparen, könnte man diesen in das TopMenu moven.

![FortschrittButtonMobile](https://user-images.githubusercontent.com/12298922/74739268-c8f01b80-5258-11ea-9212-250aa84b2e8a.png)
![FortschrittButtonTablet](https://user-images.githubusercontent.com/12298922/74739277-cbeb0c00-5258-11ea-8112-ef636ba5d201.png)

**Comment by juliandierker** [comment]
Das scheint nicht unser einziges Problem in der mobile-view zu sein.. :)
