### ISSUE TITLE
Lückentext 2.0

### ISSUE THREAD

**Issue by Miribur** [juliandierker/yUOShi#209]
- [x] inhaltlcih korrigieren

- [x] Drop down Menü (siehe vips, studIP)

**Comment by Miribur** [comment]
«Charlotte bitte drop down menü vorbereiten

**Comment by CharlotteLuise** [comment]
Mir sind nicht ganz so viele Möglichkeiten für das Drop Down Menü eingefallen, die in dem Lücken-Zusammenhang Sinn ergeben haben. Ich hoffe, das passt so?!

**Comment by Miribur** [comment]
werde ich noch einmal dran gehen, wenn ich die Anwendung wieder öffnen kann
