### ISSUE TITLE
Instruktion 2.0

### ISSUE THREAD

**Issue by Miribur** [juliandierker/yUOShi#210]
- [ ] Pop-Up und Instruktionen werden verknüpft (reinswipen, gleiche Farbe?)

- [x] Pop-Ups nicht bei jedem Task, nur bei neuen Aufgaben

- [x] Über- und Unterschriften voneinander unterscheiden, Einheitlichkeit

- [ ] Instruktionen überprüfen

**Comment by juliandierker** [comment]
Alex könnte Mockups erstellen ->
https://www.figma.com/
