### ISSUE TITLE
D&D SDT 2.0

### ISSUE THREAD

**Issue by Miribur** [juliandierker/yUOShi#212]
- [x] statements SDT ändern (neue Sätze)

- [ ] correct array (Farben sollen wieder verschwinden, nach "Aufgabe nochmal bearbeiten"

**Comment by CharlotteLuise** [comment]
Ich habe bei den Statements jetzt mal die geändert/hinzugefügt, die wir beim Sprint beschlossen haben. Sind jetzt drei in jeder Kategorie. Gerne Feedback!

**Comment by Miribur** [comment]
finde ich gut, kann so übernommen werden!
