### ISSUE TITLE
Fallbeispiele ins Top Menü

### ISSUE THREAD

**Issue by Miribur** [juliandierker/yUOShi#216]
Die Gesichter der Kinder im Top Menü werden angezeigt, man kann sie anklicken und bekommt die Information (zB durch runterziehen)

**Comment by Miribur** [comment]
= #107

**Comment by juliandierker** [comment]
https://xd.adobe.com/view/6e53ae03-358c-4677-754d-46aec305e376-1862/?fullscreen&hints=off

**Comment by juliandierker** [comment]
https://xd.adobe.com/view/6e53ae03-358c-4677-754d-46aec305e376-1862/?fullscreen&hints=off
