### ISSUE TITLE
Namen überprüfen

### ISSUE THREAD

**Issue by Miribur** [juliandierker/yUOShi#219]
Namen sollten nicht irritierend sein

**Comment by Miribur** [comment]
Vorschläge für andere Namen
Otto --> Pascal
Yenefer --> Jenny
Tino --> Silas oder Yasin

**Comment by Miribur** [comment]
@AlexPiwowar ?

**Comment by AlexPiwowar** [comment]
Vorschläge für andere Namen (v2 AP)
Otto --> **Jan** oder **Simon** (Nicht Pascal)
Yenefer --> **Jenny** (Initial als "**Jennifer**" vorstellen und dann später in den Quests zum Kosenamen "**Jenny**" übergehen könnte)
Tino --> **Silas** oder **Yasin**
