### ISSUE TITLE
Punktevergabe

### ISSUE THREAD

**Issue by Miribur** [juliandierker/yUOShi#220]
Transparenz für Punktevergabe (wieviel bekommt man pro Aufgabe?, gibt es eine Eingangserklärung?)

Punkte anzeigen lassen und belohnung zulassen --> CSS Zähler leuchtet auf, dreht sich, ändert Farbe

**Comment by Miribur** [comment]
Wenn es noch umsetzbar ist?!
kleiner dreher oder leuchten der bekommenen Punkte

**Comment by juliandierker** [comment]
Hierzu werden wir mit Lukas Vorschläge für die Visualisierung entwerfen.
