### ISSUE TITLE
Memory 2.0 

### ISSUE THREAD

**Issue by Miribur** [juliandierker/yUOShi#221]
- [x] Zeiten verlängern (in der die Memory offen sind)

- [x] Inhalte verbessern (intr. / extr. / Interesse Alternativen)

- [x] Flackern überprüfen

**Comment by CharlotteLuise** [comment]
Zu intrinsisch und extrinsisch habe ich zwei Vorschläge gemacht. Bei Interesse habe ich gar keine Idee, wie man das Vorbildlichen könnte.. Vielleicht nehmen wir es raus?

**Comment by Miribur** [comment]
wir nehmen Interesse raus!
Von den Bildern können wir gerne die ersten Abbildungen nehmen.
