### ISSUE TITLE
Quests (Neue Quests)

### ISSUE THREAD

**Issue by juliandierker** [juliandierker/yUOShi#244]
Introobjekte sollen dem Studip-Plugin beigebracht werden - Jedem Intro-Object wird ein Quest zugewiesen, der am Ende aufgerufen wird.

- [x]  Template in React-App

- [x] Mockup @CharlotteLuise 

- [x] Backend

Konzept:
<img width="463" alt="Bildschirmfoto 2020-09-03 um 15 59 11" src="https://user-images.githubusercontent.com/18357175/92124965-bad1a900-edfe-11ea-8bf5-71d157495896.png">

**Comment by SmokyZone** [comment]
Da muss dann noch einegführt werden, dass eine Quest in StudIp nicht unbedingt eine Frage bzw. Antworten braucht
