### ISSUE TITLE
Personen-Baukasten erstellen

### ISSUE THREAD

**Issue by ilukasschneider** [juliandierker/yUOShi#247]
Es werden neue Personen mit mehr Diversität gebraucht. 

Franziska nach Datein fragen und ein File zur schnellen Erstellen von neuen Personen erstellen. 

Design der Personen soll, wenn möglich, 1:1 dem alten Design entsprechen.

**Comment by juliandierker** [comment]
Wie ist hier der aktuelle Stand :)?

**Comment by ilukasschneider** [comment]
Franziska nochmal angefragt wie es mit den Dateien aussieht. Keine Antwort...

Warten oder versuchen selber zu imitieren?
