### ISSUE TITLE
Interaktive Textform

### ISSUE THREAD

**Issue by juliandierker** [juliandierker/yUOShi#251]
Dynamische Abbildungen https://github.com/juliandierker/yUOShi/wiki/Global-Mockup

- [ ] Wie wollen wir das im Backend abbilden?

- [ ] Müssen wir im Mockup Dinge ändern?

- [ ] Was ist, wenn wir keine Lösung finden? Interaktive Mock-Ups statisch einbinden?

**Comment by ilukasschneider** [comment]
Aktuelles Mockup zu diesem Issue: https://github.com/juliandierker/yUOShi/wiki/Global-Mockup
