### ISSUE TITLE
Einheitlichker Stil | yUOShi-LevelDesign

### ISSUE THREAD

**Issue by juliandierker** [juliandierker/yUOShi#261]
- [x] Rechte Navigationsleiste mit integrierter Anzeige für die Personen 

- [x] Textfenster

- [x] Textfenster für Aufgaben

- [x] Buttons (vorwärts, zurück...)

**Comment by ilukasschneider** [comment]
https://xd.adobe.com/view/5ef7a748-3f9b-4d5c-8bd7-87007007889e-0ba4/screen/eaf26143-918d-4d26-8b4a-ee4c9c7391d3?fullscreen&hints=off

(Live-Mockup), Link bleibt immer gleich.
