### ISSUE TITLE
Rechenaufgabe überarbeiten

### ISSUE THREAD

**Issue by Miribur** [juliandierker/yUOShi#262]

**Comment by Miribur** [comment]
ist hier etwas passiert? @CharlotteLuise ? Ich habe noch nichts gemacht...

**Comment by CharlotteLuise** [comment]
Also es gibt einen Vorschlag von mir, wo keine Zahlen mehr vorkommen, sondern nur noch gerankt werden soll und die Beispiele halbwegs deutlich sind. 
Oder hatten wir da jetzt etwas ganz anderes vorgesehen?

**Comment by Miribur** [comment]
Cool! Hatte ich einfach nicht mehr auf dem Schirm! Ich schaue es mir dann jetzt mal an
