### ISSUE TITLE
Intro-Modal nicht zentiert

### ISSUE THREAD

**Issue by juliandierker** [juliandierker/yUOShi#27]
<img width="1212" alt="Bildschirmfoto 2019-06-26 um 10 46 25" src="https://user-images.githubusercontent.com/18357175/60166473-8e38ff00-9801-11e9-946b-9c14ed87435d.png">

**Comment by SmokyZone** [comment]
der css top wert ist auf 50%, was wohl irgendwie zu viel ist.
Das in eine css file zu packen sollte es fixen:
`.ui.modal {
  top: 20%;
}`

Ist aber auch eher nur ein Workaround
