### ISSUE TITLE
Neue Workspace-Structure

### ISSUE THREAD

**Issue by juliandierker** [juliandierker/yUOShi#274]
Workspace Structure gemäß [Mockup](https://xd.adobe.com/view/92a9593d-8798-4648-9a4f-500f7fae5f55-c7fa/specs/) herstellen

- [ ] Titel 

- [x] TaskTemplate

- [x] Button-Segment

- [x] Platz für Progressbar

- [x] Anpassungen auf 1080 : 800

**Comment by Miribur** [comment]
Was ist hier der Stand? @SmokyZone

**Comment by SmokyZone** [comment]
Task-Titel wird in einem anderen Issue abgehandelt
