### ISSUE TITLE
Stationen Backend

### ISSUE THREAD

**Issue by juliandierker** [juliandierker/yUOShi#277]
Das Backend wird um einen Layer "Stationen" erweitert:

Aufbau: Paket --> Stationen --> Aufgaben

- [x]  Erstellung Stationen Adapter

- [x]  Erstellung Stationen Plugin

- [x] Route für das neue Backend getStationsForPackage 

- [x] Mit Daniel besprechen (Review)

- [x]  Übergabe an Sebastian

**Comment by Miribur** [comment]
Aufbau: Level --> Stationen --> und dann je nachdem Informationen oder Aufgaben

**Comment by Miribur** [comment]
Wie ist der Stand?
