### ISSUE TITLE
Info-Elemente

### ISSUE THREAD

**Issue by juliandierker** [juliandierker/yUOShi#279]
Neben Aufgaben kann man Info-Elemente anlegen =>

Sie brauchen keine Punkte und Fortschritt wird immer angezeigt, wenn man eine Info anschaut.

- [ ] Texte markieren

- [ ] Interaktive Grafiken

- [ ] Videos

- [ ]  Modale Dialoge

**Comment by Miribur** [comment]
Wichtiger Issue!
