### ISSUE TITLE
Design-Tasks-Sammlung-Dezember

### ISSUE THREAD

**Issue by ilukasschneider** [juliandierker/yUOShi#282]
- [x] **1. Abänderung der Quick-Access-Buttons: Markieren - Notizen - Quelle (Bei Inputs)**

- [x] **3. Klassenzimmer Rework**

    - Akutelles Level im Klassenzimmer erkennbar machen
    - Klassenzimmer soll sichtbar sein
    - Akutelles Level && Levelübersicht
- [x] **4. Übergreifendes Interface: Klassenzimmer, Büro, Schulübersicht**

**Comment by Miribur** [comment]
super
