### ISSUE TITLE
Frontend School Rework / Einarbeitung

### ISSUE THREAD

**Issue by juliandierker** [juliandierker/yUOShi#286]
Einbindung des neuen Frontends 

- [ ]  SVG's in HTML einbetten

- [ ]  Navigation wiederherstellen

Mockup: https://myshare.uni-osnabrueck.de/lib/74956b20-76c5-47be-acbe-56b2365be211/file/05%20Design/07_Entw%C3%BCrfe%20u%20MockUps/Demo-Mockup.xd

**Comment by ilukasschneider** [comment]
Aktuelles Mockup zu dieser Task: https://github.com/juliandierker/yUOShi/wiki/Global-Mockup
