### ISSUE TITLE
Cloze-Task

### ISSUE THREAD

**Issue by juliandierker** [juliandierker/yUOShi#292]
- [x]  Design wie in https://myshare.uni-osnabrueck.de/lib/74956b20-76c5-47be-acbe-56b2365be211/file/05%20Design/07_Entw%C3%BCrfe%20u%20MockUps/Demo-Mockup.xd

- [x]  Funktionalität wiederherstellen

Drop-Down Version! nicht mit wörtern reintippen und hashtag
Erstmal: Dropdown aus allen Antwortmöglichkeiten für alle Cloze's erstellen. Rework - For later

**Comment by Miribur** [comment]
Drop-Down Version! nicht mit wörtern reintippen und hashtag
