### ISSUE TITLE
Drag & Drop Mehrere Container

### ISSUE THREAD

**Issue by juliandierker** [juliandierker/yUOShi#320]
Im aktuellen Drag and Drop Task ist es nur möglich max. 2 Kategorien anzuzeigen. Das soll auch für 3 bzw. max. 4 Kategorien möglich sein.

- [ ] Hierzu wird ein Mockup benötigt @ilukasschneider ( Was passiert bei Overflow? )

- [ ] Frontend: @juliandierker

**Comment by ilukasschneider** [comment]
@juliandierker Gegen Overflow: Container "Scrollable" machen? -> kein Problem mit zu vielen Elementen 

Ist das technisch möglich?

**Comment by SmokyZone** [comment]
Haben wir das Issue abgeschlossen?
