### ISSUE TITLE
rework Text-Task

### ISSUE THREAD

**Issue by juliandierker** [juliandierker/yUOShi#336]
Wieder einbinden als Aufgabentyp

**Comment by SmokyZone** [comment]
@juliandierker 
Existiert das nicht bereits? im Frontend heißt es  zwar noch **RenderTag**, es ist aber **RenderText** damit gemeint.
(Der gleiche Naming-Bug gilt für **RenderQuest.** Damit ist nämlich **RenderMulti** gemeint.)

**Comment by SmokyZone** [comment]
#263
