### ISSUE TITLE
Fallbeispiele Frontend

### ISSUE THREAD

**Issue by juliandierker** [juliandierker/yUOShi#369]
- [x] Die Fallbeispiele sollen vor dem bearbeiten eines Pakets  der Reihe nach angezeigt werden.

- [x] Die Stationen mit Aufgaben der Fallbeispiele sollen nach dem Bearbeiten aller Stationen eines Pakets angezeigt werden.

Mockup:

https://github.com/juliandierker/yUOShi/wiki/Global-Mockup

**Comment by tneverland** [comment]
@juliandierker In Stud.IP funktioniert es noch nicht, Fallbeispiele zu bearbeiten. Wie ist hier der Stand? Braucht es dazu noch ein separates Issue?

**Comment by SmokyZone** [comment]
Ist das hier fertig? @juliandierker
