### ISSUE TITLE
Studip - Stationen -> Bearbeiten Button

### ISSUE THREAD

**Issue by SmokyZone** [juliandierker/yUOShi#380]
In Stationen den Bearbeiten Button anpassen

- [ ] Umbenennen zu "Metadaten bearbeiten"
- [ ] Analog auch innerhalb der Stationen als "Metadaten bearbeiten" statt "Metadaten **B**earbeiten" benennen
- [ ] Route fixen

**Comment by tneverland** [comment]
bzw. am besten immer "Metadaten bearbeiten" (--> kleines B), und bitte auch entsprechend anpassen in den Stationen --> Da steht aktuell "Inhalte bearbeiten" und "Metadaten **B**earbeiten" (--> hier auch ein kleines b einfügen)
