### ISSUE TITLE
Progress bar landing page 

### ISSUE THREAD

**Issue by Miribur** [juliandierker/yUOShi#41]
zeitlicher / prozentualer
nicht sehr detailliert

**Comment by SmokyZone** [comment]
Was genau soll da geändert werden?

**Comment by Miribur** [comment]
das soll auf der <landing page eine komplett neue Bar werden, auf der das Semester / Schuljahr angezeigt wird

**Comment by Miribur** [comment]
da soll man dann sehen, wie weit man im Schuljahr schon ist.
