### ISSUE TITLE
Fallbeispiel einbauen

### ISSUE THREAD

**Issue by SmokyZone** [juliandierker/yUOShi#74]
Intro als normalen Component anzeigen.
Content-Dummy einbauen.
MC-Fragen mit Illustration kombinieren (Immer eine Frage hervorgehoben+Illustration)

**Comment by juliandierker** [comment]
Konkret:

Dynamisch viele Fälle können eingebunden werden.
Visualisierung im Stepwizard.
https://www.npmjs.com/package/react-step-wizard
Beispielcontent:  https://myshare.uni-osnabrueck.de/lib/74956b20-76c5-47be-acbe-56b2365be211/file/04%20Inhalte%20LV/04_Quests/Quest%20Motivation.docx

**Comment by SmokyZone** [comment]
Ist das hier schon abgeschlossen?
