### ISSUE TITLE
Punktevergabe

### ISSUE THREAD

**Issue by Miribur** [juliandierker/yUOShi#86]
einpflegen pro Aufgabe
siehe dazu 
[Lernmatrix Übersicht.xlsx](https://github.com/juliandierker/yUOShi/files/3574348/Lernmatrix.Ubersicht.xlsx)

**Comment by SmokyZone** [comment]
Warum sollen beim Schritt 4 nur 3 Punkte vergeben werden? Es sind doch 4 Ankreuzmöglichkeiten.

**Comment by SmokyZone** [comment]
Memorie Tasks sind garnicht in der Tabelle aufgelistet

**Comment by SmokyZone** [comment]
TODO: 

- [ ]  Aufgabe 3 müssen die Keywords ignoriert / gelöscht werden

- [ ] Video (Schritt 3) muss punkte geben (Issue #83)

- [ ]  Selbstbestimmungstheorie (Schritt 9) Tags entfernen

- [ ] Die Erwartungs-X-Wert Theorie (Schritt 11) Tags entfernen

- [ ] Zielsetzungtheorie Locke & Latham fehlt noch ( Issue #87)

Nachdem dies alles durchgearbeitet ist, bitte noch einmal drüberschauen, ob alles richtig ist.

**Comment by SmokyZone** [comment]
Die Lernmatrix ist nicht wirklich Aktuell
