### ISSUE TITLE
TagTask-View 

### ISSUE THREAD

**Issue by juliandierker** [juliandierker/yUOShi#96]
- [x] Textverschiebung bei klick auf das Keyword (Bilder verschieben sich)

- [x] Textlänge gleichmäßig auf die spalten aufteilen.

- [x] Silbentrennung
- [x] Mehrere gleiche Tags klickbar??

- [x] TagTask kaputt.

- [x] Weiter-Button + "Nächste Aufgabe" redundant -> Weiter wird geändert zu "Aufgabe lösen".

- [x]  Chronologie der keywords überprüfen

**Comment by SmokyZone** [comment]
https://www.npmjs.com/package/react-hyphen
